#!/bin/sh

curl -sL https://github.com/upfluence/etcdenv/releases/download/v0.5.0/etcdenv-linux-amd64-0.5.0 \
 > etcdenv

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o vulcand-healthcheck

docker build --no-cache -t upfluence/vulcand-healthcheck:latest .
docker push upfluence/vulcand-healthcheck
